name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci